progress = true

[data]
    email = "twopizza9621536@gmail.com"
    name = "Samuel Wu"

[diff]
    pager = "delta"

[merge]
    command = "code"
    args = ["-w", "-m", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
