progress = true
encryption = "gpg"

[data]
    email = "twopizza9621536@gmail.com"
    name = "Samuel Wu"

[diff]
    pager = "delta"

[gpg]
    recipient = "5804F6DF89820B7B6F9E8A5E598117FC783D70FD"

[merge]
    command = "code"
    args = ["-w", "-m", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
