# [".config/tmux/plugins/tpm"]
# type = "git-repo"
# url = "https://github.com/tmux-plugins/tpm.git"
# exact = true

[".config/nano/extra"]
type = "git-repo"
url = "https://github.com/scopatz/nanorc.git"
