[".config/zsh/antidote"]
type = "git-repo"
url = "https://github.com/mattmc3/antidote.git"
refreshPeriod = "168h"

[".config/nano/extra"]
type = "git-repo"
url = "https://github.com/scopatz/nanorc.git"
