#!/usr/bin/zsh
#
# .zstyles - Set zstyle settings for plugins that need them.
#

#
# Antidote
#

zstyle ':antidote:bundle' file $ZDOTDIR/zplugins.txt
zstyle ':antidote:bundle' use-friendly-names 'yes'

#
# FZF-Tab
#

[[ -z "$TMUX" ]] && zstyle ':fzf-tab:*' fzf-command
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:*' switch-group ',' '.'
